name: GIT_MANIPULATION

  on:
    push:
      branches: [ main ]

    workflow_dispatch:

  jobs:
    manipulation:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        -name: git manipulation;
         run: |
          ls -la
