name: GITHUB

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  github-info:
    runs-on: ubuntu-latest

     with:
      github_token: ${{ github.token }}

    steps:
      - uses: actions/checkout@v2

      - name: Git info
        run: |
          git status
          git --version
          git remote -v
          git branch
          git checkout main
          git status
