name: GITHUB

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  github-info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git info
        run: |
          git status
          git --version
          git remote -v
