name: MERGE

on:
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  merging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Merge Dev to master
        run: |
          echo Start merging process...
          git checkout main
          git merge dev